#!/bin/bash
# Start script for chickens
# Generated by Mission Control

PROJECT_NAME="chickens"
PID_FILE="/tmp/${PROJECT_NAME}.pid"
PORT=5177

cd "$(dirname "$0")"

# Stop existing if running
if [ -f "$PID_FILE" ]; then
    OLD_PID=$(cat "$PID_FILE")
    if kill -0 "$OLD_PID" 2>/dev/null; then
        echo "Stopping existing $PROJECT_NAME (PID: $OLD_PID)..."
        kill "$OLD_PID"
        sleep 1
    fi
    rm -f "$PID_FILE"
fi

# TODO: Update this with actual start command
# Examples:
# - Python HTTP server: python3 -m http.server $PORT &
# - Node/Vite: npm run dev -- --port $PORT &
# - Python/FastAPI: uvicorn main:app --port $PORT &

echo "Starting $PROJECT_NAME on port $PORT..."

# Placeholder - replace with actual start command
echo "Edit this script to add your start command"
# echo $! > "$PID_FILE"
